# Generated by Django 3.0.5 on 2020-05-09 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('hash', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('mimetype', models.TextField()),
                ('scan_version', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('thumbnail_version', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata_json', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FilePath',
            fields=[
                ('path', models.TextField(primary_key=True, serialize=False)),
                ('folder', models.TextField(db_index=True)),
                ('filename', models.TextField(db_index=True)),
                ('st_mtime_ns', models.BigIntegerField()),
                ('file', models.ForeignKey(db_column='file_hash', on_delete=django.db.models.deletion.PROTECT, related_name='paths', to='vgloss.File')),
            ],
        ),
    ]
