# Generated by Django 3.0.7 on 2020-07-03 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vgloss', '0002_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filetag',
            name='file',
            field=models.ForeignKey(db_column='file_hash', on_delete=django.db.models.deletion.CASCADE, to='vgloss.File'),
        ),
        migrations.AlterUniqueTogether(
            name='filetag',
            unique_together={('file', 'tag')},
        ),
    ]
